// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9sTiQza7X31v6dgOKowNMB9k2jUPX9uc',
    appId: '1:455970770744:web:91921b255ffd8274c9bbcd',
    messagingSenderId: '455970770744',
    projectId: 'nature-dd0d2',
    authDomain: 'nature-dd0d2.firebaseapp.com',
    storageBucket: 'nature-dd0d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz608y58sF86MTU-Cje8kAzVpPot3EOo8',
    appId: '1:455970770744:android:f64c3dd1f5d309f8c9bbcd',
    messagingSenderId: '455970770744',
    projectId: 'nature-dd0d2',
    storageBucket: 'nature-dd0d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpewVq6QczI38gCTjUFEFMH80kGfAwwA',
    appId: '1:455970770744:ios:6ee5104eac1ead84c9bbcd',
    messagingSenderId: '455970770744',
    projectId: 'nature-dd0d2',
    storageBucket: 'nature-dd0d2.appspot.com',
    iosBundleId: 'com.example.nature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpewVq6QczI38gCTjUFEFMH80kGfAwwA',
    appId: '1:455970770744:ios:44e7e62f26cdbcf0c9bbcd',
    messagingSenderId: '455970770744',
    projectId: 'nature-dd0d2',
    storageBucket: 'nature-dd0d2.appspot.com',
    iosBundleId: 'com.example.nature.RunnerTests',
  );
}
